export { default as Doctors } from "./Doctors";
export { default as AddDoctor } from "./AddDoctor";
export { default as GenerateBill } from "./GenerateBill";
export { default as Print } from "./Print";
export { default as PrintRemark } from "./PrintRemark";
export { default as Bill } from "./Bill";
export { default as Jobs } from "./Jobs";
export { default as AddJob } from "./AddJob";
export { default as EditJob } from "./EditJob";
