export { default as Jobs } from "./Jobs";
export { default as Doctors } from "./Doctors";
export { default as EditDoctor } from "./EditDoctor";
export { default as Account } from "./Account";
export { default as EditJob } from "./EditJob";
export { default as EditBill } from "./EditBill";
export { default as ViewBill } from "./ViewBill";
export { default as Bills } from "./Bills";
export { default as EditPayment } from "./EditPayment";
